version: '2'
services:
    elasticsearch:
        image: elasticsearch:2.4.6
        volumes:
             - "./esdata:/usr/share/elasticsearch/data"
        ports:
            - 9200:9200
            - 9300:9300

        container_name: es-docker

