version: '2'

services:
    mysql:
        extends:
            file:    ./mysql/docker-compose.yml
            service: mysql

        volumes:
            # montando il progetto da linux non si riesce a scrivere su share win
            # serve la creazione in locale dei path dati
            - "~/docker_data/mysql:/var/lib/mysql"
      
    es:
        # funziona: crea correttamente la cartella in questa directory
        volumes:
             #- "./es/esdata:/usr/share/elasticsearch/data"             
             - "~/docker_data/esdata:/usr/share/elasticsearch/data"             
        extends:
            # "service is a required property"
            service: elasticsearch
            #
            # questa immagine non ha il plugin delete-by-query
            #
            #file:   ../nested-services-v2/elasticsearch/docker-compose.yml
            #
            #
            #
            file:   ./es/docker-compose.yml
            #
            # funziona anche questo
            #
            #file: ../../dibek/elasticsearch/docker-compose.yml
            
        #command: /usr/share/elasticsearch/bin/plugin install delete-by-query
        
        ports:
            - 9200:9200
            - 9300:9300

    php:
        environment:
            DB_HOST     : mysql
            DB_USER     : root
            DB_PASSWORD : p@ssw0rd
            DB_DATABASE : ecommerce
            
            ES_HOST     : es
        extends:
            file:    ./php/docker-compose.yml
            service: php
