version: '2'

services:
    website:
        image: php:apache
        volumes:
          #- ./website:/var/www/html
          - ./html:/var/www/html
        ports:
          - 5000:80
        #depends_on:
        #  - product-service
