FROM elasticsearch:2.4.6

#
# la versione 2.4.6 non supporta l'endpoint _delete_by_query
# supporta l'endpoint _query con action DELETE
# è necessario installarlo
#
# l'alternativa è usare una immagine più recente
#
RUN /usr/share/elasticsearch/bin/plugin install delete-by-query



EXPOSE 9200
EXPOSE 9300
#ENTRYPOINT [ "apache2-foreground" ]