FROM elasticsearch:2.4.6

RUN /usr/share/elasticsearch/bin/plugin install delete-by-query

#RUN docker-php-source extract \
#	&& docker-php-ext-install mysqli pdo pdo_mysql \
#	&& docker-php-source delete
EXPOSE 9200
EXPOSE 9300
#ENTRYPOINT [ "apache2-foreground" ]