FROM php:apache

#RUN docker-php-ext-install mysqli

RUN docker-php-source extract \
	&& docker-php-ext-install mysqli pdo pdo_mysql \
	&& docker-php-source delete

#ENTRYPOINT [ "apache2-foreground" ]
